### ISSUE TITLE
[Chat] iPad rotation issues

### ISSUE THREAD

**Issue by drewbarontini** [christfellowshipchurch/apollos-app#173]
When rotating the iPad, there are random and sporadic behaviors with the text field and the size of the chat.

**Comment by rkdavidson** [comment]
Additional details provided from **Caleb** and **Rob**:

> I’m seeing this issue on my ipad! It happen when I
> 1. open the CF App
> 2. turn to landscape
> 3. open live stream
> 4. turn to portrait
> The key thing on my end is that you have to have your device in landscape _before_ opening up a chat

Rob saw chat get in a stuck state after the transition from portrait to landscape:
<img src="https://user-images.githubusercontent.com/1812955/96735207-51473300-1389-11eb-9de7-7a0b53fa9a41.png" width="380" />

**Comment by rkdavidson** [comment]
Closing since we probably fixed or obviated this during CF 6.0 release.
