### ISSUE TITLE
Audit fonts to reduce bundle size

### ISSUE THREAD

**Issue by jordanwade** [christfellowshipchurch/apollos-app#174]

**Comment by asleepingpanda** [comment]
@jordanwade do you know if we're able to use our custom gotham font as a part of the Android build? If so, I _think_ that we might be able to remove references to the "Droid" font.

**Comment by jordanwade** [comment]
@asleepingpanda It looks like the Android app is using the Gotham font correctly. I think `DroidSerif` is still being used in the app for scripture from core. It doesn't look like the serif fonts are not being overridden in `theme.js`. 

This [PR]( https://github.com/christfellowshipchurch/apollos-app/pull/196) I did recently removes Inter-ui font and a bunch of unused Gotham font weight/types. So going to close this issue since that was merged.
