### ISSUE TITLE
Groups queries need to be updated for leaders and avatars

### ISSUE THREAD

**Issue by jordanwade** [christfellowshipchurch/apollos-app#179]
Group and volunteer queries need to be updated because of changes in this api [PR](https://github.com/christfellowshipchurch/apollos-api/pull/144). I think @asleepingpanda app [PR](https://github.com/christfellowshipchurch/apollos-app/pull/178/files) will fix this issue. We just need to confirm that then we can close this issue when that is merged.

![image](https://user-images.githubusercontent.com/2528817/97193128-a9f64180-1776-11eb-8d2b-6143dae51549.png)
![image](https://user-images.githubusercontent.com/2528817/97193190-bbd7e480-1776-11eb-9ded-939cfefdd1ee.png)

**Comment by asleepingpanda** [comment]
I think I have a branch open for this. Let me confirm that though.

**Comment by jordanwade** [comment]
Cool, I think it is this one https://github.com/christfellowshipchurch/apollos-app/pull/178

**Comment by asleepingpanda** [comment]
@jordanwade I think we're good to close this one down??

**Comment by asleepingpanda** [comment]
Here is the [Group Card fragment](https://github.com/christfellowshipchurch/apollos-app/blob/master/loadConfig.js#L267) as well as the [Group Single query](https://github.com/christfellowshipchurch/apollos-app/blob/master/src/group-single/getGroup.js#L24)

Both of these remove references to `leaders` and `avatars` in favor of `leaders` and `members` as an alias for the `people` field.
