### ISSUE TITLE
[Group Chat] Back button takes you back to Profile, not group

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/apollos-app#182]
When in a group's chat, hitting the back button takes you to the Profile tab root instead of back to the group's detail page.
I.e. it goes back "two steps" instead of one.

**Comment by asleepingpanda** [comment]
@rkdavidson is this good to close??

**Comment by rkdavidson** [comment]
I don't think so — I haven't specifically tried to fix this yet, so unless it was fixed on accident (one can hope! 🙃), it's still an issue.

**Comment by jordanwade** [comment]
@rkdavidson, I'm working on this issue and wondering do you think we need the title of the the group in the group chat? I can see how you would want to keep the context of where you are, but I can't decide if it is necessary if you click in to the group chat from the group single screen. I think I prefer the standard modal header style that has the close icon in the top right. Thoughts?

![image](https://user-images.githubusercontent.com/2528817/100939849-9dbf7b80-34bc-11eb-88af-5bc3df0385e4.png)

**Comment by rkdavidson** [comment]
@jordanwade I'm ok with that, if it's a simple change!

IIRC a lot of the architecture of that `Channel` navigation route came from the Stream components, including the title and back button.

So we could definitely wrest some control back and use the standard CF nav instead, or at least the header with the modal close etc.
